[package]
name = "densky-core"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.7.1"
glob = "0.3.1"
notify = "5.1.0"
pathdiff = "0.2.1"
colored = "2"

dynamic-html = { path = "../dynamic-html" }
