[package]
name = "densky-core"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.7.1"
glob = "0.3.1"
pathdiff = "0.2.1"
recur-fn = "2.2.0"
colored = "2"

dynamic-html = { path = "../dynamic-html", default-features = false }
prettify-js = "0.1.0"
walkdir = "2.3.3"
